services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-user}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-pass}
    volumes:
      - db_data:/data/db
    ports:
      - 127.0.0.1:${MONGO_LOCAL_PORT:-27017}:27017

  api:
    build: .
    restart: always
    command: bash ./start_web.sh
    environment:
      MONGO_HOST: ${MONGO_HOST:-localhost}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_USERNAME: ${MONGO_USERNAME:-user}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-pass}
      APP_PORT: 80
    ports:
      - 127.0.0.1:${APP_LOCAL_PORT:-8080}:80
    depends_on:
      - mongo

volumes:
  db_data:
