#!/bin/bash

# script to update the version number in the site

# goto script directory
cd "$(dirname "$0")"

# Ensure that the user has provided a valid argument
case $1 in
    patch)
        ;;
    minor)
        ;;
    major)
        ;;
    *)
        echo "Usage: $0 [patch|minor|major]"
        VERSION=$(poetry version | cut -d' ' -f2)
        echo "Current version: $VERSION"
        exit 1
        ;;
esac


# Ensure that the working directory is clean
if [[ $(git status -s) ]]
then
    echo "Working directory is not clean! Please commit all changes before running this script."
    exit 1
fi

# Ensure that the local branch is up to date with the remote branch
git pull


poetry version $1

if [ $? -ne 0 ]; then
  exit 1
fi


# get current package version by poetry
VERSION=$(poetry version | cut -d' ' -f2)

git commit -am v${VERSION}
git tag -a -m v${VERSION} v${VERSION}
git push --follow-tags
